<a href="https://colab.research.google.com/github/AmrHassanKhalaf/ITI_Camp_AI/blob/main/Pandas%2BPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1

The file "Purchase_Data.csv" contains purchase data at a Chinese supermarket for various products.  Read this csv into a dataframe called df_data and use the head() method to check that you have read in the data correctly. Make sure you import pandas.

# Step 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Step 2: Import pandas
import pandas as pd
import numpy as np

file_path = '/content/drive/MyDrive/Data/Grades.csv'
df = pd.read_csv(file_path)


print("CSV file loaded successfully! Here are the first few rows:")
print(df.head())

In [21]:
#Write your code here
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np

file_path = '/content/drive/MyDrive/Data/Purchase_Data.csv'
df = pd.read_csv(file_path)

df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Use the dtypes attribute to view how each column is stored

In [22]:
#Write your code here
df.dtypes

invoice_number    float64
invoice_time       object
store_id           object
product_id          int64
category_id         int64
num_item          float64
price             float64
dtype: object

Slice the first two columns using .loc and store the result in a variable called result_1.

In [23]:
#Write you code here
result_1=df.loc[:,['invoice_number','invoice_time']]
result_1

      invoice_number   invoice_time
0       2.020000e+11  7/15/15 10:45
1       2.020000e+11  7/15/15 12:16
2       2.020000e+11  7/15/15 12:16
3       2.020000e+11  7/15/15 12:16
4       2.020000e+11  7/15/15 12:16
...              ...            ...
5377    2.020000e+11   9/5/15 23:07
5378    2.020000e+11   9/5/15 23:23
5379    2.020000e+11   9/5/15 23:24
5380    2.020000e+11   9/5/15 23:32
5381    2.020000e+11   9/5/15 23:38

[5382 rows x 2 columns]

Slice the first two rows using .loc and store the result in a variable called result_2.

In [24]:
#Write you code here
result_2=df.loc[0:1,:]
result_2

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0

Slice the first four rows and the first five columns and store the result in a variable called result_3.

In [25]:
#Write your code here
result_3=df.iloc[0:4,0:5]
result_3

   invoice_number   invoice_time store_id  product_id  category_id
0    2.020000e+11  7/15/15 10:45     G816     7000300       210101
1    2.020000e+11  7/15/15 12:16     G816     7070884        70203
2    2.020000e+11  7/15/15 12:16     G816     7070884        70203
3    2.020000e+11  7/15/15 12:16     G816     7070891        70401

Slice rows 0,4,6 and columns invoice time and price and store the result in variable called result_4.

In [26]:
#Write your code here
result_4=df.loc[[0,4,6],['invoice_time','price']]
result_4

    invoice_time  price
0  7/15/15 10:45    2.0
4  7/15/15 12:16    6.0
6  7/15/15 15:28    2.0

Store the number rows in a variable called num_rows.

In [27]:
num_rows=df.shape[0]
num_rows

5382

Print out the last row of the data to dataframe. **Hint:** use the variable num_rows from the previous exercise.

In [49]:
#Write your code here
last_row = df.iloc[num_rows - 1]
print(last_row)

invoice_number    202000000000.0
invoice_time        9/5/15 23:38
store_id                    G619
product_id              23030206
category_id               210101
num_item                     1.0
price                        2.0
Name: 5381, dtype: object

# Part 2

Compute the average and max price charged.  Store the results in variables called avg_price and max_price

In [50]:
#Write your code here
avg_price,max_price=df['price'].mean(),df['price'].max()
avg_price,max_price

(np.float64(3.1920522110741363), 6.01)

Compute the average price and average number of items purchased with only a single call to the mean() method. Store these averages in avg_price and avg_num_items.

In [51]:
#Write you code here
avg_price,avg_num_items=df[['price','num_item']].mean()
avg_price,avg_num_items

(3.1920522110741363, 1.2983091787439613)

Create a column called "total", which is the product of the price and num_item columns.

In [52]:
#Write your code here
df['total']=df['price']*df['num_item']
df

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,total
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0,6.0
...,...,...,...,...,...,...,...,...
5377,2.020000e+11,9/5/15 23:07,300,7308017,210101,1.0,3.0,3.0
5378,2.020000e+11,9/5/15 23:23,G619,7070891,70401,1.0,6.0,6.0
5379,2.020000e+11,9/5/15 23:24,G619,7071096,70201,1.0,5.0,5.0
5380,2.020000e+11,9/5/15 23:32,G619,15000231,70301,2.0,2.0,4.0
5381,2.020000e+11,9/5/15 23:38,G619,23030206,210101,1.0,2.0,2.0

What is the avgerage price of the three most expensive purchases?

In [53]:
#Write your code here
avg_price_most_expensive=df.nlargest(3,'price')['price'].mean()
avg_price_most_expensive

np.float64(6.003333333333333)

How many different products are there?

In [55]:
#Write your code here
num_products=df['product_id'].nunique()
num_products

53

Find the difference between the mean and median of the column total.  Use the describe() method and then index the dataframe it returns.

In [56]:
#Write your code here
difference=df['total'].describe()['mean']-df['total'].describe()['50%']
difference

np.float64(0.9318078781127839)

Use the drop() method to delete the column total from the dataframe df_data.

In [57]:
#Write your code here
df_data=df.drop('total',axis=1)
df_data

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0
...,...,...,...,...,...,...,...
5377,2.020000e+11,9/5/15 23:07,300,7308017,210101,1.0,3.0
5378,2.020000e+11,9/5/15 23:23,G619,7070891,70401,1.0,6.0
5379,2.020000e+11,9/5/15 23:24,G619,7071096,70201,1.0,5.0
5380,2.020000e+11,9/5/15 23:32,G619,15000231,70301,2.0,2.0
5381,2.020000e+11,9/5/15 23:38,G619,23030206,210101,1.0,2.0

Let's dig a little deeper into the data set and answer some basic question.

In [59]:
#Write your code here
df.describe()

,invoice_number,product_id,category_id,num_item,price,total
count,5.382000e+03,5.382000e+03,5382.000000,5382.000000,5382.000000,5382.000000
mean,2.020000e+11,8.740911e+06,115465.616499,1.298309,3.192052,3.931808
std,0.000000e+00,5.048294e+06,65448.435316,2.168725,1.652007,5.820520
min,2.020000e+11,7.000034e+06,70101.000000,0.500000,0.000000,0.000000
25%,2.020000e+11,7.070884e+06,70201.000000,1.000000,2.000000,2.000000
50%,2.020000e+11,7.071096e+06,70401.000000,1.000000,2.500000,3.000000
75%,2.020000e+11,7.090592e+06,210101.000000,1.000000,5.000000,5.000000
max,2.020000e+11,3.000077e+07,210301.000000,116.000000,6.010000,348.000000

First, covert the column invoice time to a datetime column. Print out the new column types to make sure this was done correctly

In [62]:
#Write your code here
df['invoice_time']=pd.to_datetime(df['invoice_time'])
df.dtypes

/tmp/ipython-input-1640771283.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['invoice_time']=pd.to_datetime(df['invoice_time'])

invoice_number           float64
invoice_time      datetime64[ns]
store_id                  object
product_id                 int64
category_id                int64
num_item                 float64
price                    float64
total                    float64
dtype: object

Next, let's create columns called "DOW" and "Month", which store the corresponding weekday and month of the invoice respectively.  Print the head of the dataframe to make sure this was done correctly.

In [63]:
#Write your code here
Dow=df['invoice_time'].dt.day_name()
Month=df['invoice_time'].dt.month
df['DOW']=Dow
df['Month']=Month
df.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,total,DOW,Month
0,2.020000e+11,2015-07-15 10:45:00,G816,7000300,210101,1.0,2.0,2.0,Wednesday,7
1,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,2.0,Wednesday,7
2,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,2.0,Wednesday,7
3,2.020000e+11,2015-07-15 12:16:00,G816,7070891,70401,1.0,6.0,6.0,Wednesday,7
4,2.020000e+11,2015-07-15 12:16:00,G816,7090363,70401,1.0,6.0,6.0,Wednesday,7

Create a variable called num_purchases_wed, which stores the number of purchases made on Wednesday?  You should use value_counts and then index the series it return.

In [64]:
#Write your code here
cr=df['DOW'].value_counts()
num_purchases_wed=cr['Wednesday']
num_purchases_wed

np.int64(959)

# Part 3

In this set of practice exercises, we will be working with a demographic data regarding the passengers aboard the Titanic.  Read in the data frame and use the head() method to check that it was read in correctly.

In [65]:
#Write your code here
file_path = '/content/drive/MyDrive/Data/Titanic.csv'
df = pd.read_csv(file_path)

df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Use the rename method to change the column "Name" to "Passenger_Name" and the column "Ticket" to "Ticket_Num".

In [66]:
#Write your code here
re=df.rename(columns={'Name':'Passenger_Name','Ticket':'Ticket_Num'})
re

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

Change the index of the df_titanic to the column PasengerID.

In [67]:
#Write your code here
ind=df.set_index('PassengerId')
ind

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...
1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

Select the name of passenger 896

In [68]:
#Write your code here
name=df.loc[df['PassengerId']==896,'Name']
name

4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)
Name: Name, dtype: object

Change the index back to row numbers but making sure that we don't lose the PassengerId column.

In [69]:
#Write your code here
df = df.reset_index(drop=False)
display(df.head())

,index,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

How many missing entries are there in the Age column? Use the isnull() method and recall than Booleans are exactly like 1s (True) and 0s (False).

In [70]:
#Write you code here
df.isnull().sum()

index            0
PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

Compute the avg age of passengers ignoring the missing data.

In [71]:
#Write your code here
avg_age=df['Age'].mean()
avg_age

np.float64(30.272590361445783)

Using the fillna() method replace the missing values in the Age column with the mean.

In [72]:
#Write your code here
df.fillna(avg_age,inplace=True)
df

,index,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,892,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,30.27259,Q
1,1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,30.27259,S
2,2,894,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,30.27259,Q
3,3,895,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,30.27259,S
4,4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,30.27259,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,413,1305,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,30.27259,S
414,414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C
415,415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,30.27259,S
416,416,1308,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,30.27259,S
417,417,1309,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,30.27259,C

What is the average age of the 5 oldest passengers? The reset_index method will be helpful here.

In [73]:
#Write your code here
avg=df.nlargest(5, 'Age')['Age'].mean()
avg

np.float64(67.0)